### ISSUE TITLE
Configure FaunaDB for the schema

### ISSUE THREAD

**Issue by deekshasharma** [deekshasharma/subscribe-and-bill#1]
### Summary
This will enable ACME Inc to store, read, update and delete data for customer, billing, usage tracking and invoicing within a FaunaDB database.

### Intended Outcome
The middleware service-api layer needs to perform certain operations on a database. The completion of this epic will allow the service-api layer to talk to this database to persist data and support CRUD operations for subscriptions, billing and invoicing. This will be done using the GraphQL APIs supported by Fauna to access the collections within a database

### How will it work?
Created database will have all the collections setup and ready for use as mentioned in [this database schema document](https://deeksha25.atlassian.net/wiki/spaces/DT/pages/425985/Database+Schema?atlOrigin=eyJpIjoiZDJhZDA4OWY0NmFmNGM4MmFkOWM0MWIxMzA1OWQ1MTQiLCJwIjoiaiJ9) 

### Tasks Involved
- [ ] Database relationships should be documented using an ER Diagram.
- [x] Database should have all the collections created.
- [ ] The core collections should be filled up with the data needed to start using the database. For ex: plan information and metering limits should already exist in the database.
- [ ] #4

**Comment by deekshasharma** [comment]
### Summary
This will enable ACME Inc to store, read, update and delete data for customer, billing, usage tracking and invoicing within a FaunaDB database.

### Intended Outcome
The middleware service-api layer needs to perform certain operations on a database. The completion of this epic will allow the service-api layer to talk to this database to persist data and support CRUD operations for subscriptions, billing and invoicing. This will be done using the GraphQL APIs supported by Fauna to access the collections within a database

### How will it work?
Created database will have all the collections setup and ready for use as mentioned in this database schema document
