### ISSUE TITLE
Implement a middleware/service-api to communicate b/w UI and database

### ISSUE THREAD

**Issue by deekshasharma** [deekshasharma/subscribe-and-bill#2]
# Summary

This middleware service-api will enable ACME front-end app to communicate with the database in response to the user actions.

# Intended Outcome
This middleware/service-api will keep the front-end code decoupled instead of interacting with the backend database directly. The front-end app will communicate with this layer via GraphQL APIs.

# How will it work?
The service-api will be implemented and deployed separately. It will be consumed by the ACME front-end app for operations including but not limited to: login to app, creation of a new customer, CRUD operations on subscription and invoice, retrieval of usage metrics.

# Tasks Involved

## Set up related

- [x] Create a git repository with `Node.js` and `TypeScript` as the base.
- [x] Set up `eslint` and  `prettify`.
- [x] Configure the start, test , lint scripts ready in the `package.json` file. Make sure to use Husky pre-commit hook for linting.
- [ ] Configure gitHub Actions to execute tests and generate a build. Every build should be deployed to Vercel.
- [x] Set up Apollo GraphQL server without federation for receiving HTTP requests.
- [ ] The repo should be well documented using a README.md file.

### CRUD GraphQL APIs for customers
- [ ] When user sign up for a plan, a new customer should be created via create mutation.
- [ ] Update customer mutation to persist updates to customer data.
- [ ] Customer query to read the customer data.

### CRUD GraphQL APIs for subscriptions
- [ ] When user sign up for a plan, a new subscription should be created.
- [ ] There should be a way to update the subscription.
- [ ] There should be a way to read the subscription.

### GraphQL API for plans
- [ ] There should be a way to read the plan information.

### GraphQL API for plan items
- [ ] There should be a way to read the plan items given a `plan_id`

### GraphQL API for usage
- [ ] There should be a way to read the resource usage given a customer id and date range. This should return random usage at the moment. We do not have a way to track usage such as API calls for this MVP.

### CRUD GraphQL APIs for invoices
- [ ] There should be a way to create customer invoice given the data.
- [ ] There should be a way to update the invoice.
- [ ] There should be a way to read the invoice. [We won't display the invoice on the front-end. It can be downloaded using a DOWNLOAD button.]

## Stripe related
- [ ] Add customer to Stripe and set up payment for future use via Stripe node SDK.
- [ ] Take action on Stripe payment failed.
- [ ] Take action on Stripe payment success.
- [ ] Take action when a payment method is deleted from the profile.
- [ ] Take action when payment method is added.

## Slack related
- [ ] Post on slack when a new customer sign up for a plan.
- [ ] Post on slack when payment fails.
- [ ] Post on slack when subscription plan is renewed.
- [ ] Post on slack when subscription plan is upgraded or downgraded.

**Comment by deekshasharma** [comment]
### Summary

This middleware service-api will enable ACME front-end to communicate with the database in response to the user actions.


### Intended Outcome
This middleware/service-api will keep the front-end code decoupled instead of interacting with the backend database directly. The front-end app will communicate with this layer via GraphQL APIs.

### How will it work?
In order to consider this project a success, the service-api should be ready to be consumed by the front end for operations including but not limited to, login to app, creation of a new customer, CRUD operations on subscription and invoice, retrieval of usage metrics.

### Tasks Involved
- [ ] 
- [ ] 
- [ ]
