### ISSUE TITLE
Front-end app for user to select and access subscription plan

### ISSUE THREAD

**Issue by deekshasharma** [deekshasharma/subscribe-and-bill#3]
### Summary

This feature enables ACME end-users to sign up for the service and select a subscription plan of their choice.

### Intended Outcome
ACME users currently sign up to for the service and have no way to select a paid or FREE plan. With this new feature, they will be able to select and activate a subscription plan of their choice. Additionally, they add credit card to their account which will be set up for automatic recurring payments.

### How will it work?
Below capabilities will be available to users:

- [ ]  A user will be offered a selection of subscription plans at the time of sign up. It can choose a FREE plan in which case a new subscription will be created and activated for the user. 
- [ ] User will be able to upgrade and downgrade the plan anytime and will be able to review the terms and conditions.
- [ ]  The plan will be renewed on the 1st of every month. If the user is under the free limits, the credit card will not be charged for $0. If the user is on a paid plan or has exhausted the free limits on the plan, it will be charged for the overages as per the plan information.
- [ ]  An invoice will be generated every month and available under invoices section as per the design.
- [ ]  User will be able to view the current balance on the UI.
- [ ] User will be able view the current and previous invoices with an ability to download the PDF document.
- [ ]  User will be able to add and remove the payment method from their account.
- [ ]  User should be able to view the information about the current plan.

The UI should be implemented based on [this Figma prototype](https://www.figma.com/file/sNBkW2k0pHmtcptY9g05Vn/Billing-payments-invoicing?node-id=803%3A9203)

**Comment by deekshasharma** [comment]
### Summary

This feature enables ACME end-users to sign up for the service and select a subscription plan of their choice.


### Intended Outcome
ACME users currently sign up to for the service and have no way to select a paid or FREE plan. With this new feature, they will be able to select and activate a subscription plan of their choice. Additionally, they add credit card to their account which will be set up for automatic recurring payments.

### How will it work?
Below are the possible workflows

1. A user will be offered a selection of subscription plans at the time of sign up. It can choose a FREE plan in which case a new subscription will be created and activated for the user. 
2. The plan will be renewed on the 1st of every month and an invoice will be generated. If the user is under the free limits, an invoice of $0 will be generated and available under invoices section. If the user is on a paid plan or has exhausted the free limits on the plan, it will be charged for the overages which will be listed on the invoice.

### Tasks Involved
- [ ] 
- [ ] 
- [ ]
